language: node_js
cache: yarn
before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
matrix:
  include:
  - node_js: "6"
    script: yarn run test-ci
  - node_js: "8"
    script: yarn run test-ci-partial
